hash-format = "sha256"

[[files]]
file = "_config.yml"
hash = "485e7574c4a5fcb8433e32d7bcaea2a0f0be2db482b06bba1abc7b8d6957221e"

[[files]]
file = "config/tpshud_v2.json"
hash = "0a8466a293d40a79c189bb29db1fc0243bb58039a0cdfa7ff9327eda627dddd6"

[[files]]
file = "config/wpit.json5"
hash = "bbb10020301a419cff37221d2225ac9650eb73d1807fd90bfa076d277927e644"

[[files]]
file = "mods/antighost.pw.toml"
hash = "939d73cc5d76ad6c49de09d586ea3bfca1959c54c2518948c495e3114e4d5cb7"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b99f8b297b9429f5185c84805d1a67f650bba836cf83c6c9d81b275261169672"
metafile = true

[[files]]
file = "mods/axolotl-bucket-fix.pw.toml"
hash = "14337a459231e6156b331a5ed3fa881f9c55e45fd5e4794ad8489c64e8396f65"
metafile = true

[[files]]
file = "mods/beenfo.pw.toml"
hash = "27a145220af5b044739ae1b414a0fa1a44d55de811867f69a7b4eed82425a949"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "757207131774e618e46c6c0ad407c8ba7c45d3c9c4fb59ffa8209d1bfe04a0d8"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "cb813029826c5dcbbd9deee45f82e913f51a7e37b488bb330781908d25957ad6"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "c3d82e10126c56b018d25f664e9107a583091b82548c4f04a14c3b1b4db0f507"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "af1eb4731779edc72e1e1cb1664dd74328e0edb1da05805a0a694b10c48d010b"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "3eb404aa3e5431eb0d5c38c0996b97db033fed570efe4b0a852fa183c56858ce"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "b46ae91063839b3aaa7a863f69586e00883a6c98b2959005eaff27a459aa5d82"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "955b5160e856fbc93b615ad021e78421383177db29a1b0bc451e2840ad659f79"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "749bf88d67ff9ddf272dc48d82402dd61ea2812238dfca4feb1fd78440675456"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "cb14cb30c723d1ed83f1d612b61b12134ea3a39fcff3ae02c2aedc2c1aa12a67"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "e9ae0492006c9a6bc309bee3658dcc6ebb96d213f74f6285bac4ae26ffc67631"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "d562db5edffe81d5698a1c8ee6a42c4d014865dad4daf19fd4331b99018a2537"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
hash = "9c5f9f193893085d4a6f5ec4da7ad47af3350142868cd9220857297c34059694"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "6cb34219f7edaae938e9f4edabe1ee15742c6784d59dc97fc3e6df4a5e24d850"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "68a7ae55f43cf6c9ddf2e3e091705538bfc5d20b7e24b38afaa4e221bbcd3979"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "9ae76046167e451e37eb846a72b8ff2b04b997767b717b37f4c8c586f08a5ef6"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "200797c3f731a126fad409a7afa6e737af4a1e860a0d6954b48b18bb0922f3ec"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "3e84222a0d8020efe132dff80b2fc01ff9a1768dcc39f5e41a80bf7cf501a628"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "0c7c2c37874d5341092e6c63f95f4f95d7fa804e1c28ea9e83c1ed5115dcf12f"
metafile = true

[[files]]
file = "mods/horsestatsvanilla.pw.toml"
hash = "944753da8bcdf23432cec7a559f0681146b0eef0c18f5b94a952b85d20f52fad"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "bbbf79e3bc952411d58fb20119792dda0096b42784ff9398c5febd2a137153c4"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e516d6d036f6d407a793c3b9a1fc5a8a817b05c9dc9d8677003fb0a512b2bf6f"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a2bb983e5dffe95d1f92ee19a099ed214f9b3d39c4e9f8eb5991a1a3c7735b45"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "2ea587bc28af997f2b93de69af32b8ba0120ce8a2c0e95624a0c55051eb25041"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0ab0925b9d00ddcf75dc5077fba4eee2c825945a7590750e1821ba783fb26f37"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lanterns-bow.pw.toml"
hash = "f181811ad47a50bc7d722fb60b5916c5f381bd0ff55736d14c087b5c46d28bdf"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "cbd6b97dfc49090b18480f43eeef4401144006ed406110f32fb1126d47a21f11"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f264c166b22cf93af5e44a3d65931e2a46008d11ee0cd81f209a3af54979a760"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
hash = "e5e9697602c898198e19b6066305491623972d3c93855d5c0b56551a2c40039b"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "dc1f47a526f2264dc215437a81668d54c084d5beaaa6cbf6e284b88a59af88b5"
metafile = true

[[files]]
file = "mods/moderate-loading-screen.pw.toml"
hash = "b25df1d67a39156449d8888fd7df73689ec1bd0ed2e255ee076ef3f926f2f875"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f0a7c49ae4417a753722da78046a7513e059e5964e21154f4aef50df6a1d6ed0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "8f554f10f3ca26505c1f51871263a7d75fca1e07a288c60c1a96b18f830beede"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "01efbdcb32ff6e70b6777e26df46bbe3c6c5aecb3e0c81797d234dfad9e0568d"
metafile = true

[[files]]
file = "mods/numeral-ping.pw.toml"
hash = "d66a3e2d8bd4e887e659460567a311f2a184a191be157804c757890f92d143d4"
metafile = true

[[files]]
file = "mods/perfect-accuracy.pw.toml"
hash = "f537d9fc4be086fce37e6b74438e87f4b07ee913e33bd14d370eac525ccc936e"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
hash = "ec14e6c8f75a292eec280012772b63dc3d4258f51806ec20a29ad2b96e76979c"
metafile = true

[[files]]
file = "mods/plushie.pw.toml"
hash = "91c8f12f4b35547f32d868157c5d869f4ef7c31214f717c3ef76effc176700bc"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b4d8e22f7916c1a2e8be07b708cd02d16bd730e382bb7ca36a615cf3e6782940"
metafile = true

[[files]]
file = "mods/roundaround-pickup-notifications.pw.toml"
hash = "9c863029519f4a4f521ffeaf3554b0db4b7badbb3e93e5e2ffd8d0c734ca3290"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "8e81543992fe3ce4dab725e2f32f877e0f28eb7c806c178958f5c472f59f1dd8"
metafile = true

[[files]]
file = "mods/sleep-warp.pw.toml"
hash = "320c6865e322a7d6d8ec60bd2189132c52ee973af10ed255a8aac7cc26ae170e"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8bdc3c1b5079b7fbe89f995d1a100e1df8dcf47e73ef089abf444ecc8e320527"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/somemusicdiscs.pw.toml"
hash = "7a2a95adc693438be4823329bd00813a7552b6f0227df2d59a152de84bf2ed95"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "0212996355de904aa968661624fd9230d1b31d85b201b9ab01bb9e94ac0fe73c"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "ed4f37e1da3fdca4a23f5704f76604929820a2167bb0be6daeb65298afba3cba"
metafile = true

[[files]]
file = "mods/tps-hud.pw.toml"
hash = "b5acdc11c059303b13aa673f4a365a67aa69de97e9ebe24efb46cf67015bd5b8"
metafile = true

[[files]]
file = "mods/wpit.pw.toml"
hash = "37ed429dd51235c55d2dcb11649211b0065580af3b18f28db248935095c1d3e8"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "677e6eb10c7aa494473d1c9b55eaf54e4389ac19f7131564a153f81b43da45f2"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "5e14ee3730e67f5f210ec4797bb9420073403ec1925e755c43c802b38a76ad19"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "eda1cc1a41819d633cc5161ea985aa3f4cbf8f7901496bbde160c885ea808628"
metafile = true
