hash-format = "sha256"

[[files]]
file = "_config.yml"
hash = "485e7574c4a5fcb8433e32d7bcaea2a0f0be2db482b06bba1abc7b8d6957221e"

[[files]]
file = "config/options.txt"
hash = "5731f302bcbaff0def660e82e0d70156738d7aa1c49dc90bab091d5153391a77"

[[files]]
file = "config/yosbr/config/farsight.json"
hash = "4eeb4805fea7f848781675d12a2da395696d2d7e02bb177113e005bb996e9202"

[[files]]
file = "config/yosbr/config/lowfire.json"
hash = "7e9133ea5090a32536237ebc069095e3c445d42b13572122bb1de507ecd8e897"

[[files]]
file = "config/yosbr/config/shulkerboxtooltip.json5"
hash = "216e197355f772da28706eed826816b73d10f52a05db75291bf9d4b302149e21"

[[files]]
file = "config/yosbr/config/timestamp_chat.toml"
hash = "c7f3fea7982dea7d7d5df4f1707ba58ad736ec6edeab20acf597e0803de95bb6"

[[files]]
file = "config/yosbr/config/wpit.json5"
hash = "bbb10020301a419cff37221d2225ac9650eb73d1807fd90bfa076d277927e644"

[[files]]
file = "config/yosbr/options.txt"
hash = "64736dfe35a3fd4a97b435a82a14d81005e50510e911b0456b1e8b332829c2fc"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "6e6eaefbfaef2bcc5f1fae83112b3a6ab311c84ef776f389d13d49a500a52217"
metafile = true

[[files]]
file = "mods/afkdisplay.pw.toml"
hash = "bf98d18aef6550c2d85ad9c28afc05929ce54a17cefce9e38aefe70340162a87"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "939d73cc5d76ad6c49de09d586ea3bfca1959c54c2518948c495e3114e4d5cb7"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b99f8b297b9429f5185c84805d1a67f650bba836cf83c6c9d81b275261169672"
metafile = true

[[files]]
file = "mods/axolotl-bucket-fix.pw.toml"
hash = "14337a459231e6156b331a5ed3fa881f9c55e45fd5e4794ad8489c64e8396f65"
metafile = true

[[files]]
file = "mods/beaconoverhaul.pw.toml"
hash = "08bf1018fc1643357429454a2c2f28080b500957ef0675ab4d2186bd95c5c7b0"
metafile = true

[[files]]
file = "mods/beenfo.pw.toml"
hash = "27a145220af5b044739ae1b414a0fa1a44d55de811867f69a7b4eed82425a949"
metafile = true

[[files]]
file = "mods/better-biome-blend.pw.toml"
hash = "aeaefb6089a1cf7635b3722aabdda71baea6e0e72547ca3bb7726400ae5b93cd"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "757207131774e618e46c6c0ad407c8ba7c45d3c9c4fb59ffa8209d1bfe04a0d8"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "309fa9d0ab190059d9a13933db512f36f01ec0b40f37fa6e919ec085c686df9e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "407fd025c6912135c7d40c238bb96fe05ea8172c403a100ed86f978fc8124c81"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "2b9d778f845e30e9111c5b02f8fc68c797ad39e2a79c7e9d88ab54fa133b100b"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "c655002fad2689f9f413134334319d1b03e2499c5b81cb9a28d9e37b7c02d706"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "b46ae91063839b3aaa7a863f69586e00883a6c98b2959005eaff27a459aa5d82"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "53fa3438ef9e1e81193f46c36cffa7c410a933de0b6793224e99bad67cbab2e3"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "749bf88d67ff9ddf272dc48d82402dd61ea2812238dfca4feb1fd78440675456"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "5e289f7ef37b75b340dde02ee3a11a92ba6d4f045fd4f67eb3647b18cf51f739"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "e9ae0492006c9a6bc309bee3658dcc6ebb96d213f74f6285bac4ae26ffc67631"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "004dbebb72fb7b4afaa12797a18c0871b78da1cc930ee0a9e65a485a99d6232b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
hash = "9c5f9f193893085d4a6f5ec4da7ad47af3350142868cd9220857297c34059694"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "6cb34219f7edaae938e9f4edabe1ee15742c6784d59dc97fc3e6df4a5e24d850"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "855e5f89a1c2d225f10927dd9bdd06aaffbc0c59b6d2c525460db6f1c9742ad5"
metafile = true

[[files]]
file = "mods/enhanced-attack-indicator.pw.toml"
hash = "60c798ad6cb06c66714ac413e3c867bc2bb8c3b0eab450e9d430142f5f732d55"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9eaeb257cd8970aa2469222f31ceb984954092a6dcf6e7be28d7330e2ea54b10"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c57ab7e92b672af93416304950b083d0b20aabe41af61d0993292dfef80744bf"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "21d01d066ea19a5235f6296882a0807db6eab71dafbed313a4a0c8c896e4bda4"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "200797c3f731a126fad409a7afa6e737af4a1e860a0d6954b48b18bb0922f3ec"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "f29e7e0c05dfa976e14613ef7d726909ef6e406bb2338ad4f434f1bf83f898d6"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "0c7c2c37874d5341092e6c63f95f4f95d7fa804e1c28ea9e83c1ed5115dcf12f"
metafile = true

[[files]]
file = "mods/horsestatsvanilla.pw.toml"
hash = "2d89ca796ad576935102b7ba64e4c53afcb3d321fd1fc21390fa0a2574c91204"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "b5ecdce430ae016b791f415ef55f6740dcfd422cdb24c2ea78e4ec677cc7921e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e516d6d036f6d407a793c3b9a1fc5a8a817b05c9dc9d8677003fb0a512b2bf6f"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "b893248407cbc155a5182b151acf50df075cef08bd0a9470c222425e8e47a809"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "2ea587bc28af997f2b93de69af32b8ba0120ce8a2c0e95624a0c55051eb25041"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0ab0925b9d00ddcf75dc5077fba4eee2c825945a7590750e1821ba783fb26f37"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lanterns-bow.pw.toml"
hash = "f181811ad47a50bc7d722fb60b5916c5f381bd0ff55736d14c087b5c46d28bdf"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "cbd6b97dfc49090b18480f43eeef4401144006ed406110f32fb1126d47a21f11"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "443104f3ae619456aefa8eaabf9dbfba4c0a227435fc7c6e2f4c89370bb6786d"
metafile = true

[[files]]
file = "mods/low-fire.pw.toml"
hash = "5891e21a1b4f0bf9293cd835ca6e5a0dc0f080425dc5c0769640d58dfc0c7107"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
hash = "aba200ac8818fe5ce59c1cb342dcd530b81e3ea85ce2e9f9c1d3a8863b8b1be7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "dc1f47a526f2264dc215437a81668d54c084d5beaaa6cbf6e284b88a59af88b5"
metafile = true

[[files]]
file = "mods/microdurability.pw.toml"
hash = "9956cade0558572c50c4c3d5ab32bccbadcffa11304b0fdcaedbe5cd4835c81d"
metafile = true

[[files]]
file = "mods/moderate-loading-screen.pw.toml"
hash = "b25df1d67a39156449d8888fd7df73689ec1bd0ed2e255ee076ef3f926f2f875"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a5c86b836f2213ad4db415d13f6ef5caa379ce348605a29224eb7703b81f1f95"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "8f554f10f3ca26505c1f51871263a7d75fca1e07a288c60c1a96b18f830beede"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d48418bcd2fa81939864dc15e2230909b945c9b618064f16cc11f9b4db581740"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "91e24178f86243b32a8516ceefd1f21b054d7c963e44f274ddfede8d8d41c027"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "01efbdcb32ff6e70b6777e26df46bbe3c6c5aecb3e0c81797d234dfad9e0568d"
metafile = true

[[files]]
file = "mods/numeral-ping.pw.toml"
hash = "d66a3e2d8bd4e887e659460567a311f2a184a191be157804c757890f92d143d4"
metafile = true

[[files]]
file = "mods/perfect-accuracy.pw.toml"
hash = "f537d9fc4be086fce37e6b74438e87f4b07ee913e33bd14d370eac525ccc936e"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
hash = "91b558433050a895a6f5b526fc401163821a539ea243d78a629763f15c5d8dc7"
metafile = true

[[files]]
file = "mods/plushie.pw.toml"
hash = "91c8f12f4b35547f32d868157c5d869f4ef7c31214f717c3ef76effc176700bc"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b4d8e22f7916c1a2e8be07b708cd02d16bd730e382bb7ca36a615cf3e6782940"
metafile = true

[[files]]
file = "mods/roundaround-inventory-management.pw.toml"
hash = "4b159d8bece833286dcecb7803df1eba823a2c10cf42f0c15483f3db1e337636"
metafile = true

[[files]]
file = "mods/roundaround-nicer-portals.pw.toml"
hash = "baf4b44db76a08ab64d4a6c3e3b0197ad71721a2d26580342a05c79e42e5e319"
metafile = true

[[files]]
file = "mods/roundaround-pickup-notifications.pw.toml"
hash = "8277a48927d924b41631d4b4ecbd3f36eec47a6e74e56f66dcddebd323f276b6"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "8e81543992fe3ce4dab725e2f32f877e0f28eb7c806c178958f5c472f59f1dd8"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "ba4fa4527a3f7beb3e653bb404a817d9878a2f2766439c41c71332a8ec97c459"
metafile = true

[[files]]
file = "mods/sleep-warp.pw.toml"
hash = "320c6865e322a7d6d8ec60bd2189132c52ee973af10ed255a8aac7cc26ae170e"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/snowyleavesplus.pw.toml"
hash = "6e5bb6f625f33fcb89780cc7635d98a68f0a804bbd2cedcd80a8c89356d1d93c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8bdc3c1b5079b7fbe89f995d1a100e1df8dcf47e73ef089abf444ecc8e320527"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/somemusicdiscs.pw.toml"
hash = "7a2a95adc693438be4823329bd00813a7552b6f0227df2d59a152de84bf2ed95"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "ab87d11245e86cef0c692250872ec7ce84437c25927c27abf311b5ebfff5e453"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/statuseffecttimer.pw.toml"
hash = "1da5f38d24b00e49108dedf43fe3dd388bade82563e5f69689d051167ea57927"
metafile = true

[[files]]
file = "mods/tabtps.pw.toml"
hash = "c57096e4e3e03f73a4c325ac5c5f2e6a69631121df13be1977cadf3884dcd407"
metafile = true

[[files]]
file = "mods/timestamp-chat.pw.toml"
hash = "7a1186d52eae263e4891861169acfca4d4e911a841c131c6b21a7350e5bcb746"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "ed4f37e1da3fdca4a23f5704f76604929820a2167bb0be6daeb65298afba3cba"
metafile = true

[[files]]
file = "mods/wpit.pw.toml"
hash = "b66c0748890e7453aedb8c085c03e7984daedc090ea7eabed7673a2973c9c232"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1eb33f86eead49f33a4e66497910f279c6d7f466da24686274f0a4b608ca9d68"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "2bc3242a6a026024a2048e0051c0efed79d159e72d6ea361da847acbc6f68da5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c6c963c8c9389d864664aabfd259e9b3909c274b56b2ff1477dac551216b3a28"
metafile = true
