hash-format = "sha256"

[[files]]
file = "_config.yml"
hash = "485e7574c4a5fcb8433e32d7bcaea2a0f0be2db482b06bba1abc7b8d6957221e"

[[files]]
file = "mods/antighost.pw.toml"
hash = "b55fd2b618f34a5bc9a59e525bfe44e60fabfd1a2ba27d42c2041fe0a226504c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "0eb121483095f83eb273f2a11cba2f920858db1db63b9897d9b9b614e0736cf1"
metafile = true

[[files]]
file = "mods/axolotl-bucket-fix.pw.toml"
hash = "14337a459231e6156b331a5ed3fa881f9c55e45fd5e4794ad8489c64e8396f65"
metafile = true

[[files]]
file = "mods/beenfo.pw.toml"
hash = "fd2c67c1262d8afc294de8dd7e5daf9e6335647557dd9628c5dcb957075b4693"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "f1558f408e99c6c0738c55957b40139a831f31f0df4a0ee251644be857e8875a"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "5e206d6a7aa7744a3322189386a7e3c4315df2dd8a1d3a648bcde498a7a3c934"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "cb813029826c5dcbbd9deee45f82e913f51a7e37b488bb330781908d25957ad6"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "f06d2023edfd505850b00538fad3e4963fd0b88e8385e1610a3cbe258a806d75"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "62bbbf3f6001250d1c9b0117557d3fd1fd726fac50abe1d3798300ff524c7ec2"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "8ae8526c86b843e89c18b5e6286d5968594b65fc24156c5886be1892f7ef3b91"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "5c02fb2a4ee687f017a6d88ead83491da27c301a34ac5d8e3e23e609e19acb76"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "f2484245aa241d76c8ed53ba9df5325bfd6e0604de66c80db7adcded55d16f85"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "88d4b7c0b3e534c3666a1395f00fde94152238ed58f57ca1be8a81e4d358aee1"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "c1793e1e46e3149582a4662710ea951b0881be163800af38284f62d65bb4ce8d"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "d562db5edffe81d5698a1c8ee6a42c4d014865dad4daf19fd4331b99018a2537"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0f8269bf3c425efd7c76d48dda7f48523ed5171fe2e341c6cb926d06c67cc9ff"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
hash = "9d59f123915a7e9976400123fe67cc238304435fd54806052efce0577173e603"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "57dbb1a37c964e8430bd2e47276bec3d9bc47af808b6deece893bd2e5e37dc2e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "68a7ae55f43cf6c9ddf2e3e091705538bfc5d20b7e24b38afaa4e221bbcd3979"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "30276f2a81d1ba18a030bf12341ed6e0b31a4fd26c362e6c98a0e82c8adddc40"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "63714e31df2f80d94d6ec6b076c5036c4fe332e01f6f65430758a5497c29f069"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "b099d354287372a42809abf504443c382c7c51b6c3a0c67449b136003966a3cd"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "60012bc9a1ea3bc93af2f1b04b2ca73e0cb51c618b6eaa8edf4b18b6a89246b1"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "b49ee14ee074461aeec7f010a852e4d4f086885619dedc5d1e1c639f352e1fa5"
metafile = true

[[files]]
file = "mods/horsestatsvanilla.pw.toml"
hash = "944753da8bcdf23432cec7a559f0681146b0eef0c18f5b94a952b85d20f52fad"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "526184e700a27678faa1085108bcc46e96a628d2824f5e5d58f40a7c00d999fb"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ea937bf0ec6bb83d0e57a0c01fc580cc3c35f11ab6bb47b2c5ddc89837b3c156"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "6d44ba495ec60b34ea73717ff34ede52784bf2cd5260eae885df1b6495a3c73a"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "fb6470f5c3ef5b049a0d7170616c96a5daed4776bd23c13c4acfed7685ad0c67"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "1877f54cf5dde79448cf19186855c43acec855fbfd1ce856fa1f6d73ab6081ad"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "a2e62ebd7ce3187f7aa004aed7e4d11975104ae590ba1d3eb0ec319c30581574"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b9606ddefb9d793349ba6cfe819986716161970ad583607e41f5717a2a3746f3"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
hash = "701707c8860777c4742f42ceb7b79c0f8b57a6eab44cfcdf2344cf750889fdf8"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "305f2c907b02624560e867f7e618b57ef518161a0f3805c7b2868ed67d99497c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "52458fcbfb2fadc64e070f1c81d1578404d5504253c1418b7c9389286232a8a1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "32ff03d872ca26815d33d5963bfd1a6af95ce1a48591b1052284dd35dc1dfe3c"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "d798b72bb24f798374d4bcf72c848c3f304c442fa08e0f900200a6a883f0345c"
metafile = true

[[files]]
file = "mods/perfect-accuracy.pw.toml"
hash = "91918742b57a9e830027a342dc0cd2c51e90868d9fa58ccca2e6089cb86bb1f3"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
hash = "1c860c99dc2230c01acf886f7d0d37e7ba56ac64cdb9101ed5400ea513df9eae"
metafile = true

[[files]]
file = "mods/powershot.pw.toml"
hash = "50e53c128caecb11771f69e4519f51c296f67308a738e9b278810fa23bca4283"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "780a122f7b97aa4a4cd0f70ae421ed79f9a6c8371227888f62f840138b0636d3"
metafile = true

[[files]]
file = "mods/sleep-warp.pw.toml"
hash = "320c6865e322a7d6d8ec60bd2189132c52ee973af10ed255a8aac7cc26ae170e"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "44753d43c1317219d09a1c6cf5cf87a8e000d4d667a7b943338fc94949cdd2a5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ff14639a937cf18188111473e9318222be02f32e66dfceef470728dbcceb27d8"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "f1f4ef9f376a6de93706f02b0e59a3972a276a3124254f95959b1bd5af146b44"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "ff2fa771f8489f4c5d9d96232ed9d14011ea4f00136c91bee5b6ef84506b9d29"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8fcef61b9a3716c080d77711259857a0a081ff33b0fd700f02f906767640f7bc"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "066427d7b09cee68b455521580ef612ea789211ae30ada1b21c9d7383b3d9dcc"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "948279b6255e60ebf7949ff7663f1cfc1af73db5d16f6235c16e32be94799932"
metafile = true
