name = "EJ-SMP"
author = "Z4npher+ssamjh"
version = "1.19-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b4005c5ba5c34eea51fd7911677875ffa0735ee09ebaa53733e30473e008040"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
