name = "EJ-SMP"
author = "Z4npher+ssamjh"
version = "1.19-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f98b4594d45b467aa5d2ea990b8c601b1d968b5700fbafbe69f7b31f52247f40"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
