name = "EJ-SMP"
author = "Z4npher+ssamjh"
version = "1.19-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "423190803b4a08fe43bef2146c20ea3044192a2d669e60f63eb8a991474b1b70"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
