name = "EJ-SMP"
author = "Z4npher+ssamjh"
version = "1.19-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a9d6fe67a00225724bc0a3f93b62ec31d324149460c80326d23d34953c7013a"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
