name = "EJ-SMP"
author = "Z4npher+ssamjh"
version = "1.19-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "962ba18c8b3eeb8cc7fc24f5cdf9d8246ca9d1b83ecd57d19861242c0af4fb32"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
