name = "EJ-SMP"
author = "Z4npher+ssamjh"
version = "1.19-1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "469041c15d43a739b4f879a7eafbba158b44eec881d639bef67108fce8d7a6f0"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
